2021-03-02 09:46:05,768 INFO    MainThread:2808 [wandb_setup.py:_flush():69] setting env: {}
2021-03-02 09:46:05,768 INFO    MainThread:2808 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-02 09:46:05,769 INFO    MainThread:2808 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210302_094605-14kqszo3\logs\debug.log
2021-03-02 09:46:05,770 INFO    MainThread:2808 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210302_094605-14kqszo3\logs\debug-internal.log
2021-03-02 09:46:05,770 INFO    MainThread:2808 [wandb_init.py:init():352] calling init triggers
2021-03-02 09:46:05,770 INFO    MainThread:2808 [wandb_init.py:init():359] wandb.init called with sweep_config: {}
config: {'dropout': 0.5, 'channels_one': 16, 'channels_two': 32, 'batch_size': 100, 'learning_rate': 0.001, 'epochs': 5}
2021-03-02 09:46:05,772 INFO    MainThread:2808 [wandb_init.py:init():401] starting backend
2021-03-02 09:46:05,772 INFO    MainThread:2808 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-02 09:46:05,792 INFO    MainThread:2808 [backend.py:ensure_launched():123] starting backend process...
2021-03-02 09:46:06,117 INFO    MainThread:2808 [backend.py:ensure_launched():128] started backend process with pid: 904
2021-03-02 09:46:06,152 INFO    MainThread:2808 [wandb_init.py:init():406] backend started and connected
2021-03-02 09:46:06,163 INFO    MainThread:2808 [wandb_init.py:init():446] updated telemetry
2021-03-02 09:46:06,198 INFO    MainThread:2808 [wandb_init.py:init():465] communicating current version
2021-03-02 09:46:11,229 INFO    MainThread:2808 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-03-02 09:46:12,819 INFO    MainThread:2808 [wandb_init.py:init():503] starting run threads in backend
2021-03-02 09:46:18,525 INFO    MainThread:2808 [wandb_run.py:_console_start():1422] atexit reg
2021-03-02 09:46:18,532 INFO    MainThread:2808 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-03-02 09:46:18,533 INFO    MainThread:2808 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-03-02 09:46:18,534 INFO    MainThread:2808 [wandb_run.py:_redirect():1336] Redirects installed.
2021-03-02 09:46:18,534 INFO    MainThread:2808 [wandb_init.py:init():527] run started, returning control to user process
2021-03-02 09:46:29,863 ERROR   MainThread:2808 [internal_api.py:execute():126] 403 response executing GraphQL.
2021-03-02 09:46:29,863 ERROR   MainThread:2808 [internal_api.py:execute():127] {"errors":[{"message":"permission denied","path":["upsertSweep"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertSweep":null}}
2021-03-02 09:46:31,588 INFO    Dummy-10  :2808 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2021-03-02 09:46:31,590 INFO    Dummy-10  :2808 [wandb_run.py:_restore():1364] restore
2021-03-02 09:46:32,071 INFO    Dummy-10  :2808 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 787
  total_bytes: 787
}

2021-03-02 09:46:34,082 INFO    Dummy-10  :2808 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7993
  total_bytes: 7993
}

2021-03-02 09:46:36,092 INFO    Dummy-10  :2808 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7993
  total_bytes: 7993
}

2021-03-02 09:46:37,820 INFO    Dummy-10  :2808 [wandb_run.py:_show_files():1737] logging synced files
