2021-03-13 21:24:16,065 INFO    Thread-8  :2416 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'test-drive', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': 'd3botkxb', 'run_id': 's3obn3yu', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-d3botkxb\\config-s3obn3yu.yaml'}
2021-03-13 21:24:16,065 INFO    Thread-8  :2416 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 21:24:16,066 INFO    Thread-8  :2416 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212416-s3obn3yu\logs\debug.log
2021-03-13 21:24:16,066 INFO    Thread-8  :2416 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212416-s3obn3yu\logs\debug-internal.log
2021-03-13 21:24:16,067 INFO    Thread-8  :2416 [wandb_init.py:init():352] calling init triggers
2021-03-13 21:24:16,067 INFO    Thread-8  :2416 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0.5, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'tanh', 'initializer': 'random', 'learning_rate': 0.0001, 'loss_func': 'mse', 'n_hidden_layers': 3, 'optimizer': 'sgd', 'size_hidden_layers': 32}
config: {}
2021-03-13 21:24:16,068 INFO    Thread-8  :2416 [wandb_init.py:init():398] wandb.init() called when a run is still active
2021-03-13 21:24:16,202 INFO    Thread-8  :2416 [wandb_run.py:finish():1078] finishing run -my/test-drive/s3obn3yu
2021-03-13 21:24:16,204 INFO    Thread-8  :2416 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2021-03-13 21:24:16,212 INFO    Thread-8  :2416 [wandb_run.py:_restore():1364] restore
2021-03-13 21:24:17,507 INFO    Thread-8  :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 787
  total_bytes: 787
}

2021-03-13 21:24:19,551 INFO    Thread-8  :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3697
  total_bytes: 3697
}

2021-03-13 21:24:21,885 INFO    Thread-8  :2416 [wandb_run.py:_show_files():1737] logging synced files
2021-03-13 21:24:21,893 ERROR   MainThread:2416 [pyagent.py:_run_jobs_from_queue():231] Run s3obn3yu errored: UnboundLocalError("local variable 'outEachClassFlag' referenced before assignment",)
2021-03-13 21:24:23,330 INFO    Thread-14 :2416 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'test-drive', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': 'd3botkxb', 'run_id': '1modh77f', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-d3botkxb\\config-1modh77f.yaml'}
2021-03-13 21:24:23,331 INFO    Thread-14 :2416 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 21:24:23,332 INFO    Thread-14 :2416 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212423-1modh77f\logs\debug.log
2021-03-13 21:24:23,332 INFO    Thread-14 :2416 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212423-1modh77f\logs\debug-internal.log
2021-03-13 21:24:23,334 INFO    Thread-14 :2416 [wandb_init.py:init():352] calling init triggers
2021-03-13 21:24:23,334 INFO    Thread-14 :2416 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0.5, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 5, 'optimizer': 'nadam', 'size_hidden_layers': 64}
config: {'batch_size': 64, 'learning_rate': 0.001, 'epochs': 10, 'n_hidden_layers': 4, 'size_hidden_layers': 64, 'optimizer': 'adam'}
2021-03-13 21:24:23,336 INFO    Thread-14 :2416 [wandb_init.py:init():401] starting backend
2021-03-13 21:24:23,337 INFO    Thread-14 :2416 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-13 21:24:23,348 INFO    Thread-14 :2416 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 21:24:23,486 INFO    Thread-14 :2416 [backend.py:ensure_launched():128] started backend process with pid: 10788
2021-03-13 21:24:23,487 INFO    Thread-14 :2416 [wandb_init.py:init():406] backend started and connected
2021-03-13 21:24:23,495 INFO    Thread-14 :2416 [wandb_run.py:_config_callback():669] config_cb None None {'alpha': 0.5, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 5, 'optimizer': 'nadam', 'size_hidden_layers': 64}
2021-03-13 21:24:23,496 INFO    Thread-14 :2416 [wandb_init.py:init():446] updated telemetry
2021-03-13 21:24:23,497 INFO    Thread-14 :2416 [wandb_init.py:init():465] communicating current version
2021-03-13 21:24:26,097 INFO    Thread-14 :2416 [wandb_init.py:init():470] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 21:24:26,128 INFO    Thread-14 :2416 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-03-13 21:24:26,719 INFO    Thread-14 :2416 [wandb_init.py:init():503] starting run threads in backend
2021-03-13 21:24:30,367 INFO    Thread-14 :2416 [wandb_run.py:_console_start():1422] atexit reg
2021-03-13 21:24:30,369 INFO    Thread-14 :2416 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-03-13 21:24:30,369 INFO    Thread-14 :2416 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-03-13 21:24:30,369 INFO    Thread-14 :2416 [wandb_run.py:_redirect():1336] Redirects installed.
2021-03-13 21:24:30,369 INFO    Thread-14 :2416 [wandb_init.py:init():527] run started, returning control to user process
2021-03-13 21:24:30,394 INFO    Thread-14 :2416 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'test-drive', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': 'd3botkxb', 'run_id': '1modh77f', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-d3botkxb\\config-1modh77f.yaml'}
2021-03-13 21:24:30,394 INFO    Thread-14 :2416 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 21:24:30,395 INFO    Thread-14 :2416 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212430-1modh77f\logs\debug.log
2021-03-13 21:24:30,395 INFO    Thread-14 :2416 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212430-1modh77f\logs\debug-internal.log
2021-03-13 21:24:30,396 INFO    Thread-14 :2416 [wandb_init.py:init():352] calling init triggers
2021-03-13 21:24:30,396 INFO    Thread-14 :2416 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0.5, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 5, 'optimizer': 'nadam', 'size_hidden_layers': 64}
config: {}
2021-03-13 21:24:30,397 INFO    Thread-14 :2416 [wandb_init.py:init():398] wandb.init() called when a run is still active
2021-03-13 21:24:30,402 INFO    Thread-14 :2416 [wandb_run.py:finish():1078] finishing run -my/test-drive/1modh77f
2021-03-13 21:24:30,403 INFO    Thread-14 :2416 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2021-03-13 21:24:30,403 INFO    Thread-14 :2416 [wandb_run.py:_restore():1364] restore
2021-03-13 21:24:31,893 INFO    Thread-14 :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 787
  total_bytes: 787
}

2021-03-13 21:24:33,951 INFO    Thread-14 :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3701
  total_bytes: 3701
}

2021-03-13 21:24:35,970 INFO    Thread-14 :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3701
  total_bytes: 3701
}

2021-03-13 21:24:37,428 INFO    Thread-14 :2416 [wandb_run.py:_show_files():1737] logging synced files
2021-03-13 21:24:37,436 ERROR   MainThread:2416 [pyagent.py:_run_jobs_from_queue():231] Run 1modh77f errored: UnboundLocalError("local variable 'outEachClassFlag' referenced before assignment",)
2021-03-13 21:24:38,483 INFO    Thread-20 :2416 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'test-drive', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': 'd3botkxb', 'run_id': '5wiw1r2m', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-d3botkxb\\config-5wiw1r2m.yaml'}
2021-03-13 21:24:38,484 INFO    Thread-20 :2416 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 21:24:38,484 INFO    Thread-20 :2416 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212438-5wiw1r2m\logs\debug.log
2021-03-13 21:24:38,484 INFO    Thread-20 :2416 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212438-5wiw1r2m\logs\debug-internal.log
2021-03-13 21:24:38,485 INFO    Thread-20 :2416 [wandb_init.py:init():352] calling init triggers
2021-03-13 21:24:38,485 INFO    Thread-20 :2416 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 4, 'optimizer': 'sgd', 'size_hidden_layers': 64}
config: {'batch_size': 64, 'learning_rate': 0.001, 'epochs': 10, 'n_hidden_layers': 4, 'size_hidden_layers': 64, 'optimizer': 'adam'}
2021-03-13 21:24:38,486 INFO    Thread-20 :2416 [wandb_init.py:init():401] starting backend
2021-03-13 21:24:38,486 INFO    Thread-20 :2416 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-13 21:24:38,490 INFO    Thread-20 :2416 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 21:24:38,667 INFO    Thread-20 :2416 [backend.py:ensure_launched():128] started backend process with pid: 9872
2021-03-13 21:24:38,668 INFO    Thread-20 :2416 [wandb_init.py:init():406] backend started and connected
2021-03-13 21:24:38,676 INFO    Thread-20 :2416 [wandb_run.py:_config_callback():669] config_cb None None {'alpha': 0, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 4, 'optimizer': 'sgd', 'size_hidden_layers': 64}
2021-03-13 21:24:38,678 INFO    Thread-20 :2416 [wandb_init.py:init():446] updated telemetry
2021-03-13 21:24:38,679 INFO    Thread-20 :2416 [wandb_init.py:init():465] communicating current version
2021-03-13 21:24:41,850 INFO    Thread-20 :2416 [wandb_init.py:init():470] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 21:24:41,851 INFO    Thread-20 :2416 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-03-13 21:24:42,527 INFO    Thread-20 :2416 [wandb_init.py:init():503] starting run threads in backend
2021-03-13 21:24:47,546 INFO    Thread-20 :2416 [wandb_run.py:_console_start():1422] atexit reg
2021-03-13 21:24:47,549 INFO    Thread-20 :2416 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-03-13 21:24:47,549 INFO    Thread-20 :2416 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-03-13 21:24:47,549 INFO    Thread-20 :2416 [wandb_run.py:_redirect():1336] Redirects installed.
2021-03-13 21:24:47,550 INFO    Thread-20 :2416 [wandb_init.py:init():527] run started, returning control to user process
2021-03-13 21:24:47,620 INFO    Thread-20 :2416 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'test-drive', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': 'd3botkxb', 'run_id': '5wiw1r2m', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-d3botkxb\\config-5wiw1r2m.yaml'}
2021-03-13 21:24:47,621 INFO    Thread-20 :2416 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 21:24:47,622 INFO    Thread-20 :2416 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212447-5wiw1r2m\logs\debug.log
2021-03-13 21:24:47,622 INFO    Thread-20 :2416 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210313_212447-5wiw1r2m\logs\debug-internal.log
2021-03-13 21:24:47,623 INFO    Thread-20 :2416 [wandb_init.py:init():352] calling init triggers
2021-03-13 21:24:47,624 INFO    Thread-20 :2416 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0, 'batch_size': 32, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'random', 'learning_rate': 0.001, 'loss_func': 'mse', 'n_hidden_layers': 4, 'optimizer': 'sgd', 'size_hidden_layers': 64}
config: {}
2021-03-13 21:24:47,625 INFO    Thread-20 :2416 [wandb_init.py:init():398] wandb.init() called when a run is still active
2021-03-13 21:24:47,630 INFO    Thread-20 :2416 [wandb_run.py:finish():1078] finishing run -my/test-drive/5wiw1r2m
2021-03-13 21:24:47,630 INFO    Thread-20 :2416 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2021-03-13 21:24:47,631 INFO    Thread-20 :2416 [wandb_run.py:_restore():1364] restore
2021-03-13 21:24:49,587 INFO    Thread-20 :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
}
pusher_stats {
}

2021-03-13 21:24:51,594 INFO    Thread-20 :2416 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3697
  total_bytes: 3697
}

2021-03-13 21:24:52,978 INFO    Thread-20 :2416 [wandb_run.py:_show_files():1737] logging synced files
2021-03-13 21:24:52,984 ERROR   MainThread:2416 [pyagent.py:_run_jobs_from_queue():231] Run 5wiw1r2m errored: UnboundLocalError("local variable 'outEachClassFlag' referenced before assignment",)
2021-03-13 21:24:52,985 ERROR   MainThread:2416 [pyagent.py:_run_jobs_from_queue():242] Detected 3 failed runs in the first 60 seconds, killing sweep.
